name: wpviewer
description: view wordpress site!
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_widget_from_html: ^0.15.0
  http: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - .env
